apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plinth
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nickemma/veyronix.git
    targetRevision: main
    path: deploy
  destination:
    server: https://kubernetes.default.svc
    namespace: plinth-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plinth-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nickemma/veyronix.git
    targetRevision: main
    path: operator
  destination:
    server: https://kubernetes.default.svc
    namespace: plinth-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
